# Site settings
title: Crochet Croft
email: crochetpartyblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Crochet projects and guides
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Crochet Party
email: crochetpartyblog@gmail.com
facebook_username:
twitter_username: CrochetParty
github_username:
instagram_username: CrochetPartyBlog
linkedin_username: 
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Crochet Croft

# API settings
google_api_key:

# Build settings
markdown: kramdown
