# Site settings
title: KP Proofs
email: kpproofs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Proofreading and copy-editing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: KP Proofs
email: kpproofs@gmail.com
facebook_username:
twitter_username: KPProofs
github_username:
linkedin_username: 
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: KP Proofs

# API settings
google_api_key:

# Build settings
markdown: kramdown
