# Site settings
title: Katie Peterson
email:
description: > # this means to ignore newlines until "baseurl:"
  Katie Peterson, Research Associate, University of Cambridge Department of Clinical Neurosciences. CV and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.kapeters.com" # the base hostname & protocol for your site

# User setting
owner: Katie Peterson
email: kap45@medschl.cam.ac.uk
facebook_username:
twitter_username: kapeterson14
github_username:
linkedin_username: katie-peterson-097451165
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Katie Peterson

# API settings
google_api_key:

# Build settings
markdown: kramdown
