# Site settings
title: Peeriegurumi
email: peeriegurumi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Crochet projects and guides
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Peeriegurumi
email: peeriegurumi@gmail.com
facebook_username:
twitter_username:
github_username:
instagram_username: peeriegurumi
linkedin_username: 
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Peeriegurumi

# API settings
google_api_key:

# Build settings
markdown: kramdown
